apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sfenvs
spec:
  replicas: 1 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: sfenvs
    spec:
      containers:
      - name: sfenvs
        image: tricky42/sf-envs:latest